### ISSUE TITLE
Faild to query your url dialog

### ISSUE THREAD

**Issue by stephie-goodz** [micmro/Stylify-Me#23]
Hi there,

Thanks for your work! i'd really love to utilize this tool as it could save loads of time. I keep getting this dialog when I enter a URL "Faild to query your url"

Thanks!

**Comment by micmro** [comment]
Hi @stephie-goodz. Sorry for the delay - do you have any example URL?

This usually happens if there are some errors on the site.

**Comment by arnespremberg** [comment]
Hey guys,

here's an example that does not work:
https://www.montanwerke-brixlegg.com/en/unternehmen/

Thanks,
Arne

**Comment by micmro** [comment]
Thanks @arnespremberg. This likely has to do with the service using the now defunct PhantomJS. Will start look into updating it to puppeteer or so.

**Comment by micmro** [comment]
@stephie-goodz @arnespremberg your issue is now be fixed. Stylify got fully refactored to run in puppeteer using a newer chrome release
![stylifyme com__stylify=https%3A%2F%2Fwww montanwerke-brixlegg com%2Fen%2Funternehmen%2F](https://user-images.githubusercontent.com/1680390/166621870-320ef30f-1fc7-492d-895c-68d2dfac0abf.png)
.
